openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://192.168.1.120:5050/
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
  /register:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Created
